
services:
  phpadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '9000:80'
    environment:
      - PMA_ARBITRARY=1

  apache:
    build: .
    ports:
      - '8008:80'
    volumes:
      - ./website:/var/www/html/
    depends_on:
      - db
 
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: betan
    ports:
      - '3307:3306'
    volumes:
      - ./db:/var/lib/mysql/
      
